name: twitter_20240425
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  firebase_storage: ^11.7.4
  cloud_firestore: ^4.17.2
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  fluttertoast: ^8.2.5
  uuid: ^4.4.0
  flutter_slidable: ^3.1.0
  image_picker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/default_user_icon.png
